language: python
python: "3.5"
install:
  - pip install coveralls
  - pip install termcolor
script:
  - python -m unittest discover
  - coverage run --source= -m unittest discover
after_success: coveralls
